ER_DUP_ENTRY: Duplicate entry '600529' for key 'list.PRIMARY'
ER_DUP_ENTRY: Duplicate entry '600530' for key 'list.PRIMARY'
ER_DUP_ENTRY: Duplicate entry '600534' for key 'calllog.PRIMARY'
ER_DUP_ENTRY: Duplicate entry '600534' for key 'calllog.PRIMARY'
ER_DUP_ENTRY: Duplicate entry '600534' for key 'calllog.PRIMARY'
ER_DUP_ENTRY: Duplicate entry '600534' for key 'calllog.PRIMARY'
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\Connection.js:94:28)
    at Socket.<anonymous> (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\Connection.js:423:8)
    at Protocol.emit (events.js:315:20)
    at Protocol._delegateError (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\protocol\Protocol.js:398:10)
    at Protocol.end (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\Users\sam\Desktop\js\Rest_services\myapp\node_modules\mysql\lib\Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
